name: PluginTutorial2
main: com.github.ayumutama.PluginTutorial2.PluginTutorial2
version: 1.0
commands:
   testcmd:
      description: testcmd is test command.
      usage: /<command>
      permission: PluginTutorial2.testcmd
      permission-message: You don't have <permission>